/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/man.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/man.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Adventurer_Body">
            <skinnedMesh name="Cube063" geometry={nodes.Cube063.geometry} material={materials.Skin} skeleton={nodes.Cube063.skeleton} />
            <skinnedMesh name="Cube063_1" geometry={nodes.Cube063_1.geometry} material={materials.Green} skeleton={nodes.Cube063_1.skeleton} />
            <skinnedMesh name="Cube063_2" geometry={nodes.Cube063_2.geometry} material={materials.LightGreen} skeleton={nodes.Cube063_2.skeleton} />
          </group>
          <group name="Adventurer_Feet">
            <skinnedMesh name="Cube052" geometry={nodes.Cube052.geometry} material={materials.Grey} skeleton={nodes.Cube052.skeleton} />
            <skinnedMesh name="Cube052_1" geometry={nodes.Cube052_1.geometry} material={materials.Black} skeleton={nodes.Cube052_1.skeleton} />
          </group>
          <group name="Adventurer_Head">
            <skinnedMesh name="Cube039" geometry={nodes.Cube039.geometry} material={materials.Skin} skeleton={nodes.Cube039.skeleton} />
            <skinnedMesh name="Cube039_1" geometry={nodes.Cube039_1.geometry} material={materials.Eyebrows} skeleton={nodes.Cube039_1.skeleton} />
            <skinnedMesh name="Cube039_2" geometry={nodes.Cube039_2.geometry} material={materials.Hair} skeleton={nodes.Cube039_2.skeleton} />
            <skinnedMesh name="Cube039_3" geometry={nodes.Cube039_3.geometry} material={materials.Eye} skeleton={nodes.Cube039_3.skeleton} />
          </group>
          <group name="Adventurer_Legs">
            <skinnedMesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials.Brown} skeleton={nodes.Cube020.skeleton} />
            <skinnedMesh name="Cube020_1" geometry={nodes.Cube020_1.geometry} material={materials.Brown2} skeleton={nodes.Cube020_1.skeleton} />
          </group>
          <group name="Backpack">
            <skinnedMesh name="Plane" geometry={nodes.Plane.geometry} material={materials.Brown} skeleton={nodes.Plane.skeleton} />
            <skinnedMesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.LightGreen} skeleton={nodes.Plane_1.skeleton} />
            <skinnedMesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.Gold} skeleton={nodes.Plane_2.skeleton} />
            <skinnedMesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials.Green} skeleton={nodes.Plane_3.skeleton} />
          </group>
          <group name="Beach_Body">
            <skinnedMesh name="Cube070" geometry={nodes.Cube070.geometry} material={materials.Skin} skeleton={nodes.Cube070.skeleton} />
            <skinnedMesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials.LightBrown} skeleton={nodes.Cube070_1.skeleton} />
          </group>
          <group name="Beach_Feet">
            <skinnedMesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials.Skin} skeleton={nodes.Cube017.skeleton} />
            <skinnedMesh name="Cube017_1" geometry={nodes.Cube017_1.geometry} material={materials.Red_Dark} skeleton={nodes.Cube017_1.skeleton} />
          </group>
          <group name="Beach_Head">
            <skinnedMesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials.Skin} skeleton={nodes.Cube016.skeleton} />
            <skinnedMesh name="Cube016_1" geometry={nodes.Cube016_1.geometry} material={materials.Eyebrows} skeleton={nodes.Cube016_1.skeleton} />
            <skinnedMesh name="Cube016_2" geometry={nodes.Cube016_2.geometry} material={materials.Eye} skeleton={nodes.Cube016_2.skeleton} />
            <skinnedMesh name="Cube016_3" geometry={nodes.Cube016_3.geometry} material={materials.Hair} skeleton={nodes.Cube016_3.skeleton} />
            <skinnedMesh name="Cube016_4" geometry={nodes.Cube016_4.geometry} material={materials.Earrings} skeleton={nodes.Cube016_4.skeleton} />
          </group>
          <group name="Beach_Legs">
            <skinnedMesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials.Skin} skeleton={nodes.Cube022.skeleton} />
            <skinnedMesh name="Cube022_1" geometry={nodes.Cube022_1.geometry} material={materials.Red_Dark} skeleton={nodes.Cube022_1.skeleton} />
            <skinnedMesh name="Cube022_2" geometry={nodes.Cube022_2.geometry} material={materials.White} skeleton={nodes.Cube022_2.skeleton} />
          </group>
          <group name="Casual2_Body">
            <skinnedMesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials.Skin} skeleton={nodes.Cube010.skeleton} />
            <skinnedMesh name="Cube010_1" geometry={nodes.Cube010_1.geometry} material={materials.LightBrown} skeleton={nodes.Cube010_1.skeleton} />
          </group>
          <group name="Casual2_Feet">
            <skinnedMesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.Red_Dark} skeleton={nodes.Cube003.skeleton} />
            <skinnedMesh name="Cube003_1" geometry={nodes.Cube003_1.geometry} material={materials.White} skeleton={nodes.Cube003_1.skeleton} />
          </group>
          <group name="Casual2_Head">
            <skinnedMesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials.Skin} skeleton={nodes.Cube015.skeleton} />
            <skinnedMesh name="Cube015_1" geometry={nodes.Cube015_1.geometry} material={materials.Skin_Darker} skeleton={nodes.Cube015_1.skeleton} />
            <skinnedMesh name="Cube015_2" geometry={nodes.Cube015_2.geometry} material={materials.Eyebrows} skeleton={nodes.Cube015_2.skeleton} />
            <skinnedMesh name="Cube015_3" geometry={nodes.Cube015_3.geometry} material={materials.Hair} skeleton={nodes.Cube015_3.skeleton} />
            <skinnedMesh name="Cube015_4" geometry={nodes.Cube015_4.geometry} material={materials.Eye} skeleton={nodes.Cube015_4.skeleton} />
          </group>
          <skinnedMesh name="Casual2_Legs" geometry={nodes.Casual2_Legs.geometry} material={materials.LightBlue} skeleton={nodes.Casual2_Legs.skeleton} />
          <group name="Casual_Body">
            <skinnedMesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.Skin} skeleton={nodes.Cube008.skeleton} />
            <skinnedMesh name="Cube008_1" geometry={nodes.Cube008_1.geometry} material={materials.Purple} skeleton={nodes.Cube008_1.skeleton} />
          </group>
          <group name="Casual_Feet">
            <skinnedMesh name="Cube000" geometry={nodes.Cube000.geometry} material={materials.Purple} skeleton={nodes.Cube000.skeleton} />
            <skinnedMesh name="Cube000_1" geometry={nodes.Cube000_1.geometry} material={materials.White} skeleton={nodes.Cube000_1.skeleton} />
          </group>
          <group name="Casual_Head">
            <skinnedMesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials.Skin} skeleton={nodes.Cube014.skeleton} />
            <skinnedMesh name="Cube014_1" geometry={nodes.Cube014_1.geometry} material={materials.Eyebrows} skeleton={nodes.Cube014_1.skeleton} />
            <skinnedMesh name="Cube014_2" geometry={nodes.Cube014_2.geometry} material={materials.Eye} skeleton={nodes.Cube014_2.skeleton} />
            <skinnedMesh name="Cube014_3" geometry={nodes.Cube014_3.geometry} material={materials.Hair} skeleton={nodes.Cube014_3.skeleton} />
          </group>
          <group name="Casual_Legs">
            <skinnedMesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.Skin} skeleton={nodes.Cube005.skeleton} />
            <skinnedMesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials.LightBlue} skeleton={nodes.Cube005_1.skeleton} />
          </group>
          <group name="Farmer_Body">
            <skinnedMesh name="Cube036" geometry={nodes.Cube036.geometry} material={materials.Skin} skeleton={nodes.Cube036.skeleton} />
            <skinnedMesh name="Cube036_1" geometry={nodes.Cube036_1.geometry} material={materials.LightBlue} skeleton={nodes.Cube036_1.skeleton} />
            <skinnedMesh name="Cube036_2" geometry={nodes.Cube036_2.geometry} material={materials.Brown} skeleton={nodes.Cube036_2.skeleton} />
            <skinnedMesh name="Cube036_3" geometry={nodes.Cube036_3.geometry} material={materials.Beige} skeleton={nodes.Cube036_3.skeleton} />
          </group>
          <group name="Farmer_Feet">
            <skinnedMesh name="Cube035" geometry={nodes.Cube035.geometry} material={materials.Brown} skeleton={nodes.Cube035.skeleton} />
            <skinnedMesh name="Cube035_1" geometry={nodes.Cube035_1.geometry} material={materials.Brown2} skeleton={nodes.Cube035_1.skeleton} />
          </group>
          <group name="Farmer_Head">
            <skinnedMesh name="Cube032" geometry={nodes.Cube032.geometry} material={materials.Skin} skeleton={nodes.Cube032.skeleton} />
            <skinnedMesh name="Cube032_1" geometry={nodes.Cube032_1.geometry} material={materials.Eyebrows} skeleton={nodes.Cube032_1.skeleton} />
            <skinnedMesh name="Cube032_2" geometry={nodes.Cube032_2.geometry} material={materials.Beige} skeleton={nodes.Cube032_2.skeleton} />
            <skinnedMesh name="Cube032_3" geometry={nodes.Cube032_3.geometry} material={materials.Red} skeleton={nodes.Cube032_3.skeleton} />
            <skinnedMesh name="Cube032_4" geometry={nodes.Cube032_4.geometry} material={materials.Eye} skeleton={nodes.Cube032_4.skeleton} />
          </group>
          <skinnedMesh name="Farmer_Pants" geometry={nodes.Farmer_Pants.geometry} material={materials.LightBlue} skeleton={nodes.Farmer_Pants.skeleton} />
          <group name="Horse_Head">
            <skinnedMesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.Brown} skeleton={nodes.Cube004.skeleton} />
            <skinnedMesh name="Cube004_1" geometry={nodes.Cube004_1.geometry} material={materials.Brown2} skeleton={nodes.Cube004_1.skeleton} />
            <skinnedMesh name="Cube004_2" geometry={nodes.Cube004_2.geometry} material={materials.Eyebrows} skeleton={nodes.Cube004_2.skeleton} />
            <skinnedMesh name="Cube004_3" geometry={nodes.Cube004_3.geometry} material={materials.Black} skeleton={nodes.Cube004_3.skeleton} />
            <skinnedMesh name="Cube004_4" geometry={nodes.Cube004_4.geometry} material={materials.White} skeleton={nodes.Cube004_4.skeleton} />
            <skinnedMesh name="Cube004_5" geometry={nodes.Cube004_5.geometry} material={materials.Eye} skeleton={nodes.Cube004_5.skeleton} />
          </group>
          <group name="King_Body">
            <skinnedMesh name="Cube043" geometry={nodes.Cube043.geometry} material={materials.Skin} skeleton={nodes.Cube043.skeleton} />
            <skinnedMesh name="Cube043_1" geometry={nodes.Cube043_1.geometry} material={materials.Blue} skeleton={nodes.Cube043_1.skeleton} />
            <skinnedMesh name="Cube043_2" geometry={nodes.Cube043_2.geometry} material={materials.Metal} skeleton={nodes.Cube043_2.skeleton} />
            <skinnedMesh name="Cube043_3" geometry={nodes.Cube043_3.geometry} material={materials.Beige} skeleton={nodes.Cube043_3.skeleton} />
            <skinnedMesh name="Cube043_4" geometry={nodes.Cube043_4.geometry} material={materials.Metal_Dark} skeleton={nodes.Cube043_4.skeleton} />
          </group>
          <skinnedMesh name="King_Feet" geometry={nodes.King_Feet.geometry} material={materials.Metal} skeleton={nodes.King_Feet.skeleton} />
          <group name="King_Head">
            <skinnedMesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials.Skin} skeleton={nodes.Cube025.skeleton} />
            <skinnedMesh name="Cube025_1" geometry={nodes.Cube025_1.geometry} material={materials.Hair_White} skeleton={nodes.Cube025_1.skeleton} />
            <skinnedMesh name="Cube025_2" geometry={nodes.Cube025_2.geometry} material={materials.Gold} skeleton={nodes.Cube025_2.skeleton} />
            <skinnedMesh name="Cube025_3" geometry={nodes.Cube025_3.geometry} material={materials.Eye} skeleton={nodes.Cube025_3.skeleton} />
          </group>
          <group name="King_Legs">
            <skinnedMesh name="Cube051" geometry={nodes.Cube051.geometry} material={materials.DarkBrown} skeleton={nodes.Cube051.skeleton} />
            <skinnedMesh name="Cube051_1" geometry={nodes.Cube051_1.geometry} material={materials.Metal} skeleton={nodes.Cube051_1.skeleton} />
            <skinnedMesh name="Cube051_2" geometry={nodes.Cube051_2.geometry} material={materials.Metal_Dark} skeleton={nodes.Cube051_2.skeleton} />
          </group>
          <group name="Pistol">
            <skinnedMesh name="Cube204" geometry={nodes.Cube204.geometry} material={materials.DarkBrown} skeleton={nodes.Cube204.skeleton} />
            <skinnedMesh name="Cube204_1" geometry={nodes.Cube204_1.geometry} material={materials.Grey} skeleton={nodes.Cube204_1.skeleton} />
            <skinnedMesh name="Cube204_2" geometry={nodes.Cube204_2.geometry} material={materials.Black} skeleton={nodes.Cube204_2.skeleton} />
          </group>
          <group name="Punk_Body">
            <skinnedMesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.Skin} skeleton={nodes.Cube001.skeleton} />
            <skinnedMesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.White} skeleton={nodes.Cube001_1.skeleton} />
            <skinnedMesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials.Black} skeleton={nodes.Cube001_2.skeleton} />
          </group>
          <group name="Punk_Feet">
            <skinnedMesh name="Cube208" geometry={nodes.Cube208.geometry} material={materials.Skin} skeleton={nodes.Cube208.skeleton} />
            <skinnedMesh name="Cube208_1" geometry={nodes.Cube208_1.geometry} material={materials.Black} skeleton={nodes.Cube208_1.skeleton} />
          </group>
          <group name="Punk_Head">
            <skinnedMesh name="Cube026" geometry={nodes.Cube026.geometry} material={materials.Skin} skeleton={nodes.Cube026.skeleton} />
            <skinnedMesh name="Cube026_1" geometry={nodes.Cube026_1.geometry} material={materials.Eye} skeleton={nodes.Cube026_1.skeleton} />
            <skinnedMesh name="Cube026_2" geometry={nodes.Cube026_2.geometry} material={materials.Eyebrows} skeleton={nodes.Cube026_2.skeleton} />
            <skinnedMesh name="Cube026_3" geometry={nodes.Cube026_3.geometry} material={materials.Red_Dark} skeleton={nodes.Cube026_3.skeleton} />
            <skinnedMesh name="Cube026_4" geometry={nodes.Cube026_4.geometry} material={materials.Red} skeleton={nodes.Cube026_4.skeleton} />
            <skinnedMesh name="Cube026_5" geometry={nodes.Cube026_5.geometry} material={materials.Earrings} skeleton={nodes.Cube026_5.skeleton} />
          </group>
          <group name="Punk_Legs">
            <skinnedMesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.Skin} skeleton={nodes.Cube009.skeleton} />
            <skinnedMesh name="Cube009_1" geometry={nodes.Cube009_1.geometry} material={materials.LightBlue} skeleton={nodes.Cube009_1.skeleton} />
          </group>
          <group name="SpaceSuit_Body">
            <skinnedMesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.SciFi_Light} skeleton={nodes.Cube002.skeleton} />
            <skinnedMesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials.SciFi_Light_Accent} skeleton={nodes.Cube002_1.skeleton} />
            <skinnedMesh name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={materials.SciFi_Main} skeleton={nodes.Cube002_2.skeleton} />
            <skinnedMesh name="Cube002_3" geometry={nodes.Cube002_3.geometry} material={materials.SciFi_MainDark} skeleton={nodes.Cube002_3.skeleton} />
          </group>
          <group name="SpaceSuit_Feet">
            <skinnedMesh name="Cube047" geometry={nodes.Cube047.geometry} material={materials.SciFi_Light_Accent} skeleton={nodes.Cube047.skeleton} />
            <skinnedMesh name="Cube047_1" geometry={nodes.Cube047_1.geometry} material={materials.SciFi_Light} skeleton={nodes.Cube047_1.skeleton} />
          </group>
          <group name="SpaceSuit_Head">
            <skinnedMesh name="Cube049" geometry={nodes.Cube049.geometry} material={materials.SciFi_Light} skeleton={nodes.Cube049.skeleton} />
            <skinnedMesh name="Cube049_1" geometry={nodes.Cube049_1.geometry} material={materials.SciFi_Light_Accent} skeleton={nodes.Cube049_1.skeleton} />
            <skinnedMesh name="Cube049_2" geometry={nodes.Cube049_2.geometry} material={materials.Grey} skeleton={nodes.Cube049_2.skeleton} />
          </group>
          <group name="SpaceSuit_Legs">
            <skinnedMesh name="Cube046" geometry={nodes.Cube046.geometry} material={materials.SciFi_Main} skeleton={nodes.Cube046.skeleton} />
            <skinnedMesh name="Cube046_1" geometry={nodes.Cube046_1.geometry} material={materials.SciFi_Light} skeleton={nodes.Cube046_1.skeleton} />
            <skinnedMesh name="Cube046_2" geometry={nodes.Cube046_2.geometry} material={materials.SciFi_Light_Accent} skeleton={nodes.Cube046_2.skeleton} />
            <skinnedMesh name="Cube046_3" geometry={nodes.Cube046_3.geometry} material={materials.SciFi_MainDark} skeleton={nodes.Cube046_3.skeleton} />
          </group>
          <group name="Suit_Body">
            <skinnedMesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials.Skin} skeleton={nodes.Cube007.skeleton} />
            <skinnedMesh name="Cube007_1" geometry={nodes.Cube007_1.geometry} material={materials.Tie} skeleton={nodes.Cube007_1.skeleton} />
            <skinnedMesh name="Cube007_2" geometry={nodes.Cube007_2.geometry} material={materials.Suit} skeleton={nodes.Cube007_2.skeleton} />
            <skinnedMesh name="Cube007_3" geometry={nodes.Cube007_3.geometry} material={materials.White} skeleton={nodes.Cube007_3.skeleton} />
          </group>
          <skinnedMesh name="Suit_Feet" geometry={nodes.Suit_Feet.geometry} material={materials.Black} skeleton={nodes.Suit_Feet.skeleton} />
          <group name="Suit_Head">
            <skinnedMesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials.Skin} skeleton={nodes.Cube006.skeleton} />
            <skinnedMesh name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={materials.Eyebrows} skeleton={nodes.Cube006_1.skeleton} />
            <skinnedMesh name="Cube006_2" geometry={nodes.Cube006_2.geometry} material={materials.Hair} skeleton={nodes.Cube006_2.skeleton} />
            <skinnedMesh name="Cube006_3" geometry={nodes.Cube006_3.geometry} material={materials.Eye} skeleton={nodes.Cube006_3.skeleton} />
          </group>
          <skinnedMesh name="Suit_Legs" geometry={nodes.Suit_Legs.geometry} material={materials.Suit} skeleton={nodes.Suit_Legs.skeleton} />
          <group name="Swat_Body">
            <skinnedMesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials.Skin} skeleton={nodes.Cube018.skeleton} />
            <skinnedMesh name="Cube018_1" geometry={nodes.Cube018_1.geometry} material={materials.Swat} skeleton={nodes.Cube018_1.skeleton} />
            <skinnedMesh name="Cube018_2" geometry={nodes.Cube018_2.geometry} material={materials.Swat_Black} skeleton={nodes.Cube018_2.skeleton} />
          </group>
          <skinnedMesh name="Swat_Feet" geometry={nodes.Swat_Feet.geometry} material={materials.Swat_Black} skeleton={nodes.Swat_Feet.skeleton} />
          <group name="Swat_Head">
            <skinnedMesh name="Cube037" geometry={nodes.Cube037.geometry} material={materials.Swat_Black} skeleton={nodes.Cube037.skeleton} />
            <skinnedMesh name="Cube037_1" geometry={nodes.Cube037_1.geometry} material={materials.Swat} skeleton={nodes.Cube037_1.skeleton} />
            <skinnedMesh name="Cube037_2" geometry={nodes.Cube037_2.geometry} material={materials.Visor} skeleton={nodes.Cube037_2.skeleton} />
          </group>
          <group name="Swat_Legs">
            <skinnedMesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials.Swat} skeleton={nodes.Cube023.skeleton} />
            <skinnedMesh name="Cube023_1" geometry={nodes.Cube023_1.geometry} material={materials.Swat_Black} skeleton={nodes.Cube023_1.skeleton} />
          </group>
          <group name="Sword">
            <skinnedMesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.Metal_Dark} skeleton={nodes.Cylinder.skeleton} />
            <skinnedMesh name="Cylinder_1" geometry={nodes.Cylinder_1.geometry} material={materials.Brown} skeleton={nodes.Cylinder_1.skeleton} />
            <skinnedMesh name="Cylinder_2" geometry={nodes.Cylinder_2.geometry} material={materials.Metal} skeleton={nodes.Cylinder_2.skeleton} />
          </group>
          <group name="Worker_Body">
            <skinnedMesh name="Cube027" geometry={nodes.Cube027.geometry} material={materials.Skin} skeleton={nodes.Cube027.skeleton} />
            <skinnedMesh name="Cube027_1" geometry={nodes.Cube027_1.geometry} material={materials.Worker_Yellow} skeleton={nodes.Cube027_1.skeleton} />
            <skinnedMesh name="Cube027_2" geometry={nodes.Cube027_2.geometry} material={materials.Worker_Vest} skeleton={nodes.Cube027_2.skeleton} />
            <skinnedMesh name="Cube027_3" geometry={nodes.Cube027_3.geometry} material={materials.LightBrown} skeleton={nodes.Cube027_3.skeleton} />
          </group>
          <group name="Worker_Feet">
            <skinnedMesh name="Cube028" geometry={nodes.Cube028.geometry} material={materials.Grey} skeleton={nodes.Cube028.skeleton} />
            <skinnedMesh name="Cube028_1" geometry={nodes.Cube028_1.geometry} material={materials.Black} skeleton={nodes.Cube028_1.skeleton} />
          </group>
          <group name="Worker_Head">
            <skinnedMesh name="Cube031" geometry={nodes.Cube031.geometry} material={materials.Skin} skeleton={nodes.Cube031.skeleton} />
            <skinnedMesh name="Cube031_1" geometry={nodes.Cube031_1.geometry} material={materials.Eyebrows} skeleton={nodes.Cube031_1.skeleton} />
            <skinnedMesh name="Cube031_2" geometry={nodes.Cube031_2.geometry} material={materials.Worker_Yellow} skeleton={nodes.Cube031_2.skeleton} />
            <skinnedMesh name="Cube031_3" geometry={nodes.Cube031_3.geometry} material={materials.Moustache} skeleton={nodes.Cube031_3.skeleton} />
            <skinnedMesh name="Cube031_4" geometry={nodes.Cube031_4.geometry} material={materials.Eye} skeleton={nodes.Cube031_4.skeleton} />
          </group>
          <group name="Worker_Legs">
            <skinnedMesh name="Cube029" geometry={nodes.Cube029.geometry} material={materials.Brown} skeleton={nodes.Cube029.skeleton} />
            <skinnedMesh name="Cube029_1" geometry={nodes.Cube029_1.geometry} material={materials.Brown2} skeleton={nodes.Cube029_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/man.glb')
