/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/man.glb
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations, OrbitControls } from "@react-three/drei";
import { useCustomization } from "../contexts/Customization";
import { useFrame, useThree } from "@react-three/fiber";
import * as THREE from "three";
export const Man = (props) => {
  const { camera } = useThree();
  const { nodes, materials, animations } = useGLTF("./models/man.glb");
  const headRef = useRef();
  const bodyRef = useRef();
  const legsRef = useRef();
  const feetsRef = useRef();
  console.log(materials)

  const { ref, actions, names } = useAnimations(animations);
  const myMaterials = {
    SKIN: materials.Skin,
    EYE: materials.Eye,
    EARRINGS: materials.Earrings,
    HAIR: materials.Hair,
    TOP1: materials.LightGreen,
    TOP2: materials.Green,
    TOP3: materials.Beige,
    TOP4: materials.Brown,
    LEGS1: materials.Red,
    LEGS2: materials.Black,
    LEGS3: materials.Metal, 
    FEET1: materials.Purple,
    FEET2: materials.White,
    FEET3: materials.Blue,   
  };
  const {
    body,
    feet,
    head,
    legs,
    animationIndex,
    setTotalAnimations,
    setTotalBody,
    setTotalHead,
    setTotalFeet,
    setTotalLegs,
    setColor,
    setMaterial,
    setMeshName,
  } = useCustomization();
  setTotalAnimations(names.length);
  setTotalBody(9);
  setTotalFeet(9);
  setTotalHead(9);
  setTotalLegs(9);
  // Change animation when the index changes
  useEffect(() => {
    // Reset and fade in animation after an index has been changed
    actions[names[animationIndex]].reset().fadeIn(0.5).play();
    // In the clean-up phase, fade it out
    return () => actions[names[animationIndex]].fadeOut(0.5);
  }, [animationIndex, actions, names]);

  function rgbToHex(color) {
    const r = Math.ceil(color.r * 255);
    const g = Math.ceil(color.g * 255);
    const b = Math.ceil(color.b * 255);
    const hex = ((1 << 24) + (r << 16) + (g << 8) + b).toString(16).slice(1);
    return "#" + hex;
  }

  function handleClick(event) {
    // Prevent event bubbling
    event.stopPropagation();

    // Get the NDC of the mouse position
    const mouse = new THREE.Vector3();
    mouse.x = (event.clientX / window.innerWidth) * 2 - 1;
    mouse.y = -(event.clientY / window.innerHeight) * 2 + 1;
    mouse.z = 0.5;
    mouse.unproject(camera);

    // Set up the ray direction
    const ray = new THREE.Raycaster(
      camera.position,
      mouse.sub(camera.position).normalize()
    );

    // Get the intersections with the objects in the scene
    const intersects = ray.intersectObjects(ref.current.children, true);

    // If an object was clicked on, log its material
    for (let i = 0; i < intersects.length; i++) {
      const object = intersects[i].object;

      if (object.visible && object.material.transparent === false) {
        let parentGroup = object;
        while (parentGroup.type !== "Group") {
          parentGroup = parentGroup.parent;
        }
        if (parentGroup.visible) {
          const material = object.material;
          setMaterial(material);
          setColor(rgbToHex(material.color));
          if (material.name === "Hair" || material.name === "Skin")
            setMeshName(material.name);
          else {
            let name = "";
            const splitParent = parentGroup.name.split("_");
            let parentName = splitParent[splitParent.length - 1];
            if (parentName === "CharacterArmature") parentName = "";
            if (object.name.includes("_")) {
              const split = object.name.split("_");
              name = parentName + split[split.length - 1];
            } else {
              name = parentName + "0";
            }
            setMeshName(name);
          }
          // parentGroup.children.forEach(element => {
          //   console.log(element.material.name)
          // });

          break;
        }
      }
    }
  }

  return (
    <group ref={ref} {...props} dispose={null} onClick={handleClick}>
      <OrbitControls />
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />

          {/* HEAD */}
          <group ref={headRef} name="HEAD">
            <group name="Adventurer_Head" visible={head === 1}>
              <skinnedMesh
                name="Head"
                geometry={nodes.Cube039.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube039.skeleton}
              />
              <skinnedMesh
                name="Eyebrows"
                geometry={nodes.Cube039_1.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube039_1.skeleton}
              />
              <skinnedMesh
                name="Hair"
                geometry={nodes.Cube039_2.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube039_2.skeleton}
              />
              <skinnedMesh
                name="Eye"
                geometry={nodes.Cube039_3.geometry}
                material={myMaterials.EYE}
                skeleton={nodes.Cube039_3.skeleton}
              />
            </group>
            <group name="Beach_Head" visible={head === 2}>
              <skinnedMesh
                name="Head"
                geometry={nodes.Cube016.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube016.skeleton}
              />
              <skinnedMesh
                name="Eyebrows"
                geometry={nodes.Cube016_1.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube016_1.skeleton}
              />
              <skinnedMesh
                name="Eye"
                geometry={nodes.Cube016_2.geometry}
                material={myMaterials.EYE}
                skeleton={nodes.Cube016_2.skeleton}
              />
              <skinnedMesh
                name="Hair"
                geometry={nodes.Cube016_3.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube016_3.skeleton}
              />
              <skinnedMesh
                name="Earrings"
                geometry={nodes.Cube016_4.geometry}
                material={myMaterials.EARRINGS}
                skeleton={nodes.Cube016_4.skeleton}
              />
            </group>
            <group name="Casual2_Head" visible={head === 3}>
              <skinnedMesh
                name="Head"
                geometry={nodes.Cube015.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube015.skeleton}
              />
              <skinnedMesh
                name="Beard"
                geometry={nodes.Cube015_1.geometry}
                material={myMaterials.HAIR} /* Beard */
                skeleton={nodes.Cube015_1.skeleton}
              />
              <skinnedMesh
                name="Eyebrows"
                geometry={nodes.Cube015_2.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube015_2.skeleton}
              />
              <skinnedMesh
                name="Hair"
                geometry={nodes.Cube015_3.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube015_3.skeleton}
              />
              <skinnedMesh
                name="Eye"
                geometry={nodes.Cube015_4.geometry}
                material={myMaterials.EYE}
                skeleton={nodes.Cube015_4.skeleton}
              />
            </group>
            <group name="Casual_Head" visible={head === 4}>
              <skinnedMesh
                name="Head"
                geometry={nodes.Cube014.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube014.skeleton}
              />
              <skinnedMesh
                name="Eyebrows"
                geometry={nodes.Cube014_1.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube014_1.skeleton}
              />
              <skinnedMesh
                name="Eye"
                geometry={nodes.Cube014_2.geometry}
                material={myMaterials.EYE}
                skeleton={nodes.Cube014_2.skeleton}
              />
              <skinnedMesh
                name="Hair"
                geometry={nodes.Cube014_3.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube014_3.skeleton}
              />
            </group>
            <group name="Farmer_Head" visible={head === 5}>
              <skinnedMesh
                name="Head"
                geometry={nodes.Cube032.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube032.skeleton}
              />
              <skinnedMesh
                name="Hair"
                geometry={nodes.Cube032_1.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube032_1.skeleton}
              />
              <skinnedMesh
                name="Eye"
                geometry={nodes.Cube032_2.geometry}
                material={myMaterials.EYE}
                skeleton={nodes.Cube032_2.skeleton}
              />
            </group>
            <group name="King_Head" visible={head === 6}>
              <skinnedMesh
                name="Head"
                geometry={nodes.Cube025.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube025.skeleton}
              />
              <skinnedMesh
                name="Hair"
                geometry={nodes.Cube025_1.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube025_1.skeleton}
              />
              <skinnedMesh
                name="Eye"
                geometry={nodes.Cube025_2.geometry}
                material={myMaterials.EYE}
                skeleton={nodes.Cube025_2.skeleton}
              />
            </group>
            <group name="Punk_Head" visible={head === 7}>
              <skinnedMesh
                name="Head"
                geometry={nodes.Cube026.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube026.skeleton}
              />
              <skinnedMesh
                name="Eye"
                geometry={nodes.Cube026_1.geometry}
                material={myMaterials.EYE}
                skeleton={nodes.Cube026_1.skeleton}
              />
              <skinnedMesh
                name="Eyebrows"
                geometry={nodes.Cube026_2.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube026_2.skeleton}
              />
              <skinnedMesh
                name="Hair"
                geometry={nodes.Cube026_3.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube026_3.skeleton}
              />
              <skinnedMesh
                name="Hair1"
                geometry={nodes.Cube026_4.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube026_4.skeleton}
              />
              <skinnedMesh
                name="Earrings"
                geometry={nodes.Cube026_5.geometry}
                material={myMaterials.EARRINGS}
                skeleton={nodes.Cube026_5.skeleton}
              />
            </group>
            <group name="Suit_Head" visible={head === 8}>
              <skinnedMesh
                name="Head"
                geometry={nodes.Cube006.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube006.skeleton}
              />
              <skinnedMesh
                name="Eyebrows"
                geometry={nodes.Cube006_1.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube006_1.skeleton}
              />
              <skinnedMesh
                name="Hair"
                geometry={nodes.Cube006_2.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube006_2.skeleton}
              />
              <skinnedMesh
                name="Eye"
                geometry={nodes.Cube006_3.geometry}
                material={myMaterials.EYE}
                skeleton={nodes.Cube006_3.skeleton}
              />
            </group>
            <group name="Worker_Head" visible={head === 9}>
              <skinnedMesh
                name="Head"
                geometry={nodes.Cube031.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube031.skeleton}
              />
              <skinnedMesh
                name="Eyebrows"
                geometry={nodes.Cube031_1.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube031_1.skeleton}
              />
              <skinnedMesh
                name="Hair"
                geometry={nodes.Cube031_2.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube031_2.skeleton}
              />
              <skinnedMesh
                name="Moustache"
                geometry={nodes.Cube031_3.geometry}
                material={myMaterials.HAIR}
                skeleton={nodes.Cube031_3.skeleton}
              />
              <skinnedMesh
                name="Eye"
                geometry={nodes.Cube031_4.geometry}
                material={myMaterials.EYE}
                skeleton={nodes.Cube031_4.skeleton}
              />
            </group>
          </group>

          {/* BODY */}
          <group ref={bodyRef} name="BODY">
            <group name="Adventurer_Body" visible={body === 1}>
              <skinnedMesh
                name="Arms"
                geometry={nodes.Cube063.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube063.skeleton}
              />
              <skinnedMesh
                name="Top1"
                geometry={nodes.Cube063_1.geometry}
                material={myMaterials.TOP2}
                skeleton={nodes.Cube063_1.skeleton}
              />
              <skinnedMesh
                name="Top2"
                geometry={nodes.Cube063_2.geometry}
                material={myMaterials.TOP1}
                skeleton={nodes.Cube063_2.skeleton}
              />
            </group>
            <group name="Beach_Body" visible={body === 2}>
              <skinnedMesh
                name="Arms"
                geometry={nodes.Cube070.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube070.skeleton}
              />
              <skinnedMesh
                name="Top1"
                geometry={nodes.Cube070_1.geometry}
                material={myMaterials.TOP1}
                skeleton={nodes.Cube070_1.skeleton}
              />
            </group>
            <group name="Casual2_Body" visible={body === 3}>
              <skinnedMesh
                name="Arms"
                geometry={nodes.Cube010.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube010.skeleton}
              />
              <skinnedMesh
                name="Top1"
                geometry={nodes.Cube010_1.geometry}
                material={myMaterials.TOP1}
                skeleton={nodes.Cube010_1.skeleton}
              />
            </group>
            <group name="Casual_Body" visible={body === 4}>
              <skinnedMesh
                name="Arms"
                geometry={nodes.Cube008.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube008.skeleton}
              />
              <skinnedMesh
                name="Top1"
                geometry={nodes.Cube008_1.geometry}
                material={myMaterials.TOP1}
                skeleton={nodes.Cube008_1.skeleton}
              />
            </group>
            <group name="Farmer_Body" visible={body === 5}>
              <skinnedMesh
                name="Arms"
                geometry={nodes.Cube036.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube036.skeleton}
              />
              <skinnedMesh
                name="Top2"
                geometry={nodes.Cube036_1.geometry}
                material={myMaterials.TOP2}
                skeleton={nodes.Cube036_1.skeleton}
              />
              <skinnedMesh
                name="Top1"
                geometry={nodes.Cube036_2.geometry}
                material={myMaterials.TOP1}
                skeleton={nodes.Cube036_2.skeleton}
              />
              <skinnedMesh
                name="Top3"
                geometry={nodes.Cube036_3.geometry}
                material={myMaterials.TOP3}
                skeleton={nodes.Cube036_3.skeleton}
              />
            </group>
            <group name="King_Body" visible={body === 6}>
              <skinnedMesh
                name="Arms"
                geometry={nodes.Cube043.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube043.skeleton}
              />
              <skinnedMesh
                name="Top1"
                geometry={nodes.Cube043_1.geometry}
                material={myMaterials.TOP1}
                skeleton={nodes.Cube043_1.skeleton}
              />
              <skinnedMesh
                name="Top2"
                geometry={nodes.Cube043_2.geometry}
                material={myMaterials.TOP2}
                skeleton={nodes.Cube043_2.skeleton}
              />
              <skinnedMesh
                name="Top3"
                geometry={nodes.Cube043_3.geometry}
                material={myMaterials.TOP3}
                skeleton={nodes.Cube043_3.skeleton}
              />
              <skinnedMesh
                name="Top4"
                geometry={nodes.Cube043_4.geometry}
                material={myMaterials.TOP4}
                skeleton={nodes.Cube043_4.skeleton}
              />
            </group>
            <group name="Punk_Body" visible={body === 7}>
              <skinnedMesh
                name="Arms"
                geometry={nodes.Cube001.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube001.skeleton}
              />
              <skinnedMesh
                name="Top1"
                geometry={nodes.Cube001_1.geometry}
                material={myMaterials.TOP1}
                skeleton={nodes.Cube001_1.skeleton}
              />
              <skinnedMesh
                name="Top2"
                geometry={nodes.Cube001_2.geometry}
                material={myMaterials.TOP2}
                skeleton={nodes.Cube001_2.skeleton}
              />
            </group>
            <group name="Suit_Body" visible={body === 8}>
              <skinnedMesh
                name="Arms"
                geometry={nodes.Cube007.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube007.skeleton}
              />
              <skinnedMesh
                name="Top3"
                geometry={nodes.Cube007_1.geometry}
                material={myMaterials.TOP3}
                skeleton={nodes.Cube007_1.skeleton}
              />
              <skinnedMesh
                name="Top2"
                geometry={nodes.Cube007_2.geometry}
                material={myMaterials.TOP2}
                skeleton={nodes.Cube007_2.skeleton}
              />
              <skinnedMesh
                name="Top1"
                geometry={nodes.Cube007_3.geometry}
                material={myMaterials.TOP1}
                skeleton={nodes.Cube007_3.skeleton}
              />
            </group>
            <group name="Worker_Body" visible={body === 9}>
              <skinnedMesh
                name="Arms"
                geometry={nodes.Cube027.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube027.skeleton}
              />
              <skinnedMesh
                name="Top3"
                geometry={nodes.Cube027_1.geometry}
                material={myMaterials.TOP3}
                skeleton={nodes.Cube027_1.skeleton}
              />
              <skinnedMesh
                name="Top2"
                geometry={nodes.Cube027_2.geometry}
                material={myMaterials.TOP2}
                skeleton={nodes.Cube027_2.skeleton}
              />
              <skinnedMesh
                name="Top1"
                geometry={nodes.Cube027_3.geometry}
                material={myMaterials.TOP1}
                skeleton={nodes.Cube027_3.skeleton}
              />
            </group>
          </group>

          {/* LEGS */}
          <group ref={legsRef} name="LEGS">                                
            <group name="Adventurer_Legs" visible={legs === 1}>
              <skinnedMesh
                name="Legs1"
                geometry={nodes.Cube020.geometry}
                material={myMaterials.LEGS1}
                skeleton={nodes.Cube020.skeleton}
              />
              <skinnedMesh
                name="Legs2"
                geometry={nodes.Cube020_1.geometry}
                material={myMaterials.LEGS2}
                skeleton={nodes.Cube020_1.skeleton}
              />
            </group>
            <group name="Beach_Legs" visible={legs === 2}>
              <skinnedMesh
                name="Legs"
                geometry={nodes.Cube022.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube022.skeleton}
              />
              <skinnedMesh
                name="Legs1"
                geometry={nodes.Cube022_1.geometry}
                material={myMaterials.LEGS1}
                skeleton={nodes.Cube022_1.skeleton}
              />
              <skinnedMesh
                name="Legs2"
                geometry={nodes.Cube022_2.geometry}
                material={myMaterials.LEGS2}
                skeleton={nodes.Cube022_2.skeleton}
              />
            </group>
            <skinnedMesh
              name="Casual2_Legs" visible={legs === 3}
              geometry={nodes.Casual2_Legs.geometry}
              material={myMaterials.LEGS1}
              skeleton={nodes.Casual2_Legs.skeleton}              
            />
            <group name="Casual_Legs" visible={legs === 4}>
              <skinnedMesh
                name="Legs"
                geometry={nodes.Cube005.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube005.skeleton}
              />
              <skinnedMesh
                name="Legs1"
                geometry={nodes.Cube005_1.geometry}
                material={myMaterials.LEGS1}
                skeleton={nodes.Cube005_1.skeleton}
              />
            </group>
            <skinnedMesh
              name="Farmer_Pants"
              geometry={nodes.Farmer_Pants.geometry}
              material={myMaterials.LEGS1}
              skeleton={nodes.Farmer_Pants.skeleton}
              visible={legs === 5}
            />
            <group name="King_Legs" visible={legs === 6}>
              <skinnedMesh
                name="Legs1"
                geometry={nodes.Cube051.geometry}
                material={myMaterials.LEGS1}
                skeleton={nodes.Cube051.skeleton}
              />
              <skinnedMesh
                name="Legs2"
                geometry={nodes.Cube051_1.geometry}
                material={myMaterials.LEGS2}
                skeleton={nodes.Cube051_1.skeleton}
              />
              <skinnedMesh
                name="Legs3"
                geometry={nodes.Cube051_2.geometry}
                material={myMaterials.LEGS3}
                skeleton={nodes.Cube051_2.skeleton}
              />
            </group>
            <group name="Punk_Legs" visible={legs === 7}>
              <skinnedMesh
                name="Legs"
                geometry={nodes.Cube009.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube009.skeleton}
              />
              <skinnedMesh
                name="Legs1"
                geometry={nodes.Cube009_1.geometry}
                material={myMaterials.LEGS1}
                skeleton={nodes.Cube009_1.skeleton}
              />
            </group>
            <skinnedMesh
              name="Suit_Legs"
              geometry={nodes.Suit_Legs.geometry}
              material={myMaterials.LEGS1}
              skeleton={nodes.Suit_Legs.skeleton}
              visible={legs === 8}
            />
            <group name="Worker_Legs" visible={legs === 9}>
              <skinnedMesh
                name="Legs1"
                geometry={nodes.Cube029.geometry}
                material={myMaterials.LEGS1}
                skeleton={nodes.Cube029.skeleton}
              />
              <skinnedMesh
                name="Legs2"
                geometry={nodes.Cube029_1.geometry}
                material={myMaterials.LEGS2}
                skeleton={nodes.Cube029_1.skeleton}
              />
            </group>
          </group>

          {/* FEETS */}
          <group ref={feetsRef} name="FEETS">
            <group name="Adventurer_Feet" visible={feet === 1}>
              <skinnedMesh
                name="Feet1"
                geometry={nodes.Cube052.geometry}
                material={myMaterials.FEET1}
                skeleton={nodes.Cube052.skeleton}
              />
              <skinnedMesh
                name="Feet2"
                geometry={nodes.Cube052_1.geometry}
                material={myMaterials.FEET2}
                skeleton={nodes.Cube052_1.skeleton}
              />
            </group>
            <group name="Beach_Feet" visible={feet === 2}>
              <skinnedMesh
                name="Feet"
                geometry={nodes.Cube017.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube017.skeleton}
              />
              <skinnedMesh
                name="Feet1"
                geometry={nodes.Cube017_1.geometry}
                material={myMaterials.FEET1}
                skeleton={nodes.Cube017_1.skeleton}
              />
            </group>
            <group name="Casual2_Feet" visible={feet === 3}>
              <skinnedMesh
                name="Feet1"
                geometry={nodes.Cube003.geometry}
                material={myMaterials.FEET1}
                skeleton={nodes.Cube003.skeleton}
              />
              <skinnedMesh
                name="Feet2"
                geometry={nodes.Cube003_1.geometry}
                material={myMaterials.FEET2}
                skeleton={nodes.Cube003_1.skeleton}
              />
            </group>
            <group name="Casual_Feet" visible={feet === 4}>
              <skinnedMesh
                name="Feet1"
                geometry={nodes.Cube000.geometry}
                material={myMaterials.FEET1}
                skeleton={nodes.Cube000.skeleton}
              />
              <skinnedMesh
                name="Feet2"
                geometry={nodes.Cube000_1.geometry}
                material={myMaterials.FEET2}
                skeleton={nodes.Cube000_1.skeleton}
              />
            </group>
            <group name="Farmer_Feet" visible={feet === 5}>
              <skinnedMesh
                name="Feet1"
                geometry={nodes.Cube035.geometry}
                material={myMaterials.FEET1}
                skeleton={nodes.Cube035.skeleton}
              />
              <skinnedMesh
                name="Feet2"
                geometry={nodes.Cube035_1.geometry}
                material={myMaterials.FEET2}
                skeleton={nodes.Cube035_1.skeleton}
              />
            </group>
            <skinnedMesh
              name="King_Feet"
              geometry={nodes.King_Feet.geometry}
              material={myMaterials.FEET1}
              skeleton={nodes.King_Feet.skeleton}
              visible={feet === 6}
            />
            <group name="Punk_Feet" visible={feet === 7}>
              <skinnedMesh
                name="Feet"
                geometry={nodes.Cube208.geometry}
                material={myMaterials.SKIN}
                skeleton={nodes.Cube208.skeleton}
              />
              <skinnedMesh
                name="Feet1"
                geometry={nodes.Cube208_1.geometry}
                material={myMaterials.FEET1}
                skeleton={nodes.Cube208_1.skeleton}
              />
            </group>
            <skinnedMesh
              name="Suit_Feet"
              geometry={nodes.Suit_Feet.geometry}
              material={myMaterials.FEET1}
              skeleton={nodes.Suit_Feet.skeleton}
              visible={feet === 8}
            />
            <group name="Worker_Feet" visible={feet === 9}>
              <skinnedMesh
                name="Feet2"
                geometry={nodes.Cube028.geometry}
                material={myMaterials.FEET2}
                skeleton={nodes.Cube028.skeleton}
              />
              <skinnedMesh
                name="Feet1"
                geometry={nodes.Cube028_1.geometry}
                material={myMaterials.FEET1}
                skeleton={nodes.Cube028_1.skeleton}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("./models/man.glb");
